[package]
name = "simple-web-browser"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "swb"
path = "src/main.rs"

[dependencies]
cascade = "1.0"
dlopen = "0.1"
dlopen_derive = "0.1"
dirs = "4.0"
webkit2gtk = "0.18"

