[package]
name = "swb_bookmarks"
version = "22.225.1"
edition = "2021"

[dependencies]
gtk4 = "0.4.6"
cascade = "1.0.0"

[lib]
name = "swb_bookmarks"
crate-type = [ "cdylib" ]
path = "src/swb_bookmarks.rs"
